-- ============================================================
-- 002_projects_table.sql — Projects & PM Projects Tables
-- ============================================================
--
-- SQL CONCEPTS IN THIS FILE:
--
-- TEXT vs VARCHAR:
--   In PostgreSQL, TEXT is the preferred string type.
--   VARCHAR(n) limits length at the DB level, but Prisma/Zod handle
--   length validation in the application layer — so TEXT is cleaner.
--
-- NOT NULL:
--   Means the column cannot be empty/missing.
--   Any INSERT that omits a NOT NULL column without a default will fail.
--
-- DEFAULT:
--   Provides an automatic value if the column is omitted in an INSERT.
--   NOW() = current timestamp at the moment of insert.
--   FALSE = boolean false.
--   0 = integer zero.
--
-- UNIQUE:
--   Enforces that no two rows can have the same value in this column.
--   slug must be unique so /projects/devconnect-hub always maps to one project.
--
-- INDEX:
--   A data structure that speeds up SELECT queries on specific columns.
--   Without an index, PostgreSQL scans every row to find matches.
--   With an index, it uses a B-tree lookup — much faster.
--   Rule of thumb: add an index on columns you frequently filter/sort by.

CREATE TABLE IF NOT EXISTS projects (
  -- id: cuid() generated by Prisma, stored as TEXT
  -- cuid = "collision-resistant unique identifier" — URL-safe, sortable
  id           TEXT        PRIMARY KEY,

  -- slug: URL-friendly name like "devconnect-hub"
  -- UNIQUE ensures GET /projects/:slug always resolves to exactly one project
  slug         TEXT        NOT NULL UNIQUE,

  title        TEXT        NOT NULL,
  tag          TEXT        NOT NULL,   -- "Full-Stack · React · Node.js"
  description  TEXT        NOT NULL,
  year         TEXT        NOT NULL,   -- "2024" or "2023–now"

  -- category distinguishes engineering from pm projects
  -- CHECK constraint: only allows 'engineering' or 'pm'
  category     TEXT        NOT NULL DEFAULT 'engineering'
                           CHECK (category IN ('engineering', 'pm')),

  link_label   TEXT        NOT NULL,   -- "Case Study", "GitHub", "View Live"
  link_url     TEXT,                   -- nullable: some projects have no link yet
  image_url    TEXT,                   -- nullable: added once screenshots are ready

  featured     BOOLEAN     NOT NULL DEFAULT FALSE,
  -- `order` controls display order in the frontend (manual sorting)
  "order"      INTEGER     NOT NULL DEFAULT 0,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- TIMESTAMPTZ = timestamp WITH time zone — always store in UTC
);

-- Index on slug for fast lookups by slug
CREATE INDEX IF NOT EXISTS idx_projects_slug     ON projects (slug);
-- Index on category for filtering engineering vs pm projects
CREATE INDEX IF NOT EXISTS idx_projects_category ON projects (category);
-- Index on featured for filtering featured-only queries
CREATE INDEX IF NOT EXISTS idx_projects_featured ON projects (featured);
-- Index on order for sorted queries
CREATE INDEX IF NOT EXISTS idx_projects_order    ON projects ("order");


-- ── PM Projects Table ──────────────────────────────────────────────────────────
-- Separate table because PM projects have different fields:
--   - icon (emoji) instead of imageUrl
--   - no category column (they're all PM by definition)

CREATE TABLE IF NOT EXISTS pm_projects (
  id           TEXT        PRIMARY KEY,
  slug         TEXT        NOT NULL UNIQUE,
  title        TEXT        NOT NULL,
  tag          TEXT        NOT NULL,   -- "PM · Documentation · Notion"
  description  TEXT        NOT NULL,
  icon         TEXT        NOT NULL DEFAULT '📋',   -- Emoji or icon identifier
  year         TEXT        NOT NULL,
  link_label   TEXT        NOT NULL,
  link_url     TEXT,
  "order"      INTEGER     NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pm_projects_slug  ON pm_projects (slug);
CREATE INDEX IF NOT EXISTS idx_pm_projects_order ON pm_projects ("order");
